package com.example.demo1.controller;

import com.example.demo1.model.Admin;
import com.example.demo1.service.AdminService;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.util.List;

@WebServlet("/admin")
public class AdminController extends HttpServlet {

    private AdminService adminService;

    @Override
    public void init() throws ServletException {
        adminService = new AdminService();
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action = request.getParameter("action");

        if ("list".equals(action)) {
            List<Admin> admins = adminService.getAllAdmins();
            System.out.println("Admins fetched: " + admins.size()); // Debugging line
            request.setAttribute("admins", admins);
            request.getRequestDispatcher("/views/admin-list.jsp").forward(request, response);

        }
        else if ("view".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));
            Admin admin = adminService.getAdminById(id);
            if (admin != null) {
                request.setAttribute("admin", admin);
                request.getRequestDispatcher("/views/admin-view.jsp").forward(request, response);
            } else {
                response.sendRedirect("admin?action=list");
            }

        }

        else if ("edit".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));
            Admin admin = adminService.getAdminById(id);
            if (admin != null) {
                request.setAttribute("admin", admin);
                request.getRequestDispatcher("/views/admin-edit.jsp").forward(request, response);
            } else {
                response.sendRedirect("admin?action=list");
            }
        }
        else if ("add".equals(action)) {
            request.getRequestDispatcher("/views/admin-add.jsp").forward(request, response);
        }
        else {
            response.sendRedirect("admin?action=list");
        }
    }


    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        String action = request.getParameter("action");
        if ("add".equals(action)) {
            Admin admin = createAdminFromRequest(request);
            adminService.addAdmin(admin);
            response.sendRedirect("admin?action=list");
        }
        else if ("update".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));
            Admin admin = createAdminFromRequest(request);
            System.out.println(admin);
            admin.setAdminID(id);
            adminService.updateAdmin(admin);
            response.sendRedirect("admin?action=list");

        }
        else if ("delete".equals(action)) {
            int id = Integer.parseInt(request.getParameter("id"));
            adminService.removeAdmin(id);
            response.sendRedirect("admin?action=list");
        }
        else {
            response.sendRedirect("admin?action=list");
        }
    }

    private Admin createAdminFromRequest(HttpServletRequest request) {
        return new Admin(
                0,  // ID will be auto-generated by the database
                request.getParameter("Username"),
                request.getParameter("passwordHash"),
                request.getParameter("role")
        );
    }
}
